//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyProject.EntitiesModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jobs
    {
        public int Id { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public string JobName { get; set; }
        public string Describe { get; set; }
        public Nullable<int> DemandNum { get; set; }
        public string DemandType { get; set; }
        public Nullable<decimal> SalaryUpper { get; set; }
        public Nullable<decimal> SalaryLower { get; set; }
    
        public virtual CompanyInfo CompanyInfo { get; set; }
    }
}
