//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyProject.EntitiesModel
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class UserInfo
    {
        public int Uid { get; set; }
        [Required(ErrorMessage = "*请输入用户名")]
        [StringLength(10, MinimumLength = 4, ErrorMessage = "*长度为4~10位")]
        [Remote("CheckUsername", "User", ErrorMessage = "*该用户已存在!", HttpMethod = "post")]
        [RegularExpression(@"^[a-zA-Z0-9_-]*$", ErrorMessage = "*包含非法字符,由数字、字母、下划线组成")]
        public string Username { get; set; }
        [Required(ErrorMessage = "*请输入姓名")]
        public string Name { get; set; }
        [DataType(DataType.Password)]
        [Required(ErrorMessage = "*请输入密码")]
        public string Password { get; set; }
        [DataType(DataType.PhoneNumber, ErrorMessage = "*号码格式错误")]
        public string Tel { get; set; }
        [RegularExpression(@"^[a-zA-Z0-9_-]+@[a-zA-Z0-9_-]+(\.[a-zA-Z0-9_-]+)+$", ErrorMessage = "*邮箱格式错误")]
        public string Email { get; set; }
        public Nullable<bool> Sex { get; set; }
        public string School { get; set; }
        [DataType(DataType.MultilineText)]
        public string Describe { get; set; }
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string Knowledge { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string Specialty { get; set; }
    }
}
